config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "posts#index"
  resources :posts do
    collection do
      get 'search'
    end
    resources :comments
    resource :likes, only: [:create, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment,   presence: true

  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :title
  belongs_to :sex

    validates :title_id,        numericality: { other_than: 1, message: "を入力してください" }
  
  with_options presence: true do
    validates :disease
    validates :name
    validates :age,             numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100, allow_blank: true }
  end
    validates :sex_id,          numericality: { other_than: 1, message: "を入力してください" }
  
 with_options unless: -> { title_id == 2 } do
    with_options presence: true do
      validates :family
      validates :airway
      validates :breathing
      validates :circulation
      validates :dysfunction_cns
      validates :symptom
      validates :allergy
      validates :medicine
      validates :past_history
      validates :last_meal
      validates :event
      validates :risk_factor
      validates :story
      validates :point
      validates :images,          length: { minimum: 1, maximum: 5, message: "は1枚以上5枚以下にしてください", allow_blank: true  }
    end
  end 

  with_options if: -> { title_id == 2 } do
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100, allow_blank: true }
    validates :sex_id, numericality: { other_than: 1, message: "を入力してください" }
    validates :symptom, presence: true
  end
  
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def self.search(search)
    if search.present?
      Post.where("title_id = #{search}")
      Post.where('symptom LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/sex.rb
class Sex < ActiveHash::Base
  include ActiveHash::Associations
  has_many :posts

  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '男性' },
    { id: 3, name: '女性' },
    { id: 4, name: '不明' }
  ]
end 

app/models/title.rb
class Title < ActiveHash::Base
  include ActiveHash::Associations
  has_many :posts

  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '下書き' },
    { id: 3, name: '心停止' },
    { id: 4, name: '外傷' },
    { id: 5, name: '意識障害' },
    { id: 6, name: '内因性' },
    { id: 7, name: 'ICU' }
  ]
end 

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname,      presence: true
  validates :password,      format: { with:  /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'は半角英数を両方含む必要があります', allow_blank: true }
  validates :department,    presence: true

  has_many :posts
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :department])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_post, except: :new
  before_action :set_comment, only: [:show, :edit, :update]
  before_action :draft, only: [:index, :create, :show]

  def index
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@post)
    else 
      render :index, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
    unless current_user.id == @comment.user_id 
      redirect_to post_path(@post)
    end
  end

  def update
    @comment.update(comment_params)
    if @comment.save
      redirect_to post_comment_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    unless current_user.id == comment.user_id 
      redirect_to post_path(@post)
    else
      comment.destroy
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def draft
    if @post.title_id == 2
      redirect_to post_path(@post)
    end
  end 

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    like = current_user.likes.build(post_id: params[:post_id])
    like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_post, only: [:show, :edit, :update ]

  def index
    @post = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = @post.comments.order("created_at DESC")
  end

  def edit
    unless current_user.id == @post.user_id 
      redirect_to root_path
    end
  end

  def update
    @post.update(post_params)
    if @post.save
      redirect_to post_path(@post.id)
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    unless current_user.id == post.user_id 
      redirect_to root_path
    else
      post.destroy
      redirect_to root_path
    end
  end

  def search
    @posts_by_title = Post.where('title_id = ?', params[:title_id]).order("created_at DESC")
    @posts_by_keyword = Post.where('symptom LIKE ?', "%#{params[:keyword]}%").order("created_at DESC")
  end

  private

  def post_params
    params.require(:post)
          .permit(:title_id, :disease, :name, :age, :sex_id, :family, 
                  :airway, :breathing, :circulation, :dysfunction_cns, :exposure,
                  :symptom, :allergy, :medicine, :past_history, :last_meal, :event, :risk_factor, :others, 
                  :story, :point, {images: []})
          .merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(user_params)
  end

  def after_update_path_for(resource)
    user_path(id: resource.id)
  end
  
  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :department)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @nickname = @user.nickname
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<div class='main-body'>
  <%= render partial: "shared/side_header/comment_index", locals: { post: @post } %>
  
  <div class='menus'>
    <%= render partial: "shared/menus/comment_index", locals: { post: @post } %>
  </div>
  
  <div class='main'>
    <%= render partial: "shared/top_header/pt_name", locals: { post: @post } %>

    <div class='post-show'>
      <div class="post-info">
       <%= render partial: "shared/scenario", locals: { post: @post } %>
       <%= simple_format(@post.story)%>
      </div>
      <div class='comment-index'>
        評価ポイント<br/><br/>
        <%= simple_format(@post.point) %>
      </div>
    </div>

    <div class="comment-new">
      <%= form_with model: @comment, url: post_comment_path, class: 'comment-new-main', local: true do |f| %>
        <div class="field">
          <%= f.text_area :comment, placeholder: "" %>
        </div>
        <div class="btn-contents">
         <%= f.submit "変更する", data: { turbo_method: :get, turbo_confirm: ( render "shared/error_messages", model: f.object ) } ,class:"post-btn" %>
       </div>
    <% end %>
  </div>
</div>

app/views/comments/index.html.erb
<div class='main-body'>
  <%= render partial: "shared/side_header/comment_index", locals: { post: @post } %>
  
  <div class='menus'>
    <%= render partial: "shared/menus/comment_index", locals: { post: @post } %>
  </div>
  
  <div class='main'>
    <%= render partial: "shared/top_header/pt_name", locals: { post: @post } %>

    <div class='post-show'>
      <div class="post-info">
       <%= render partial: "shared/scenario", locals: { post: @post } %>
       <%= simple_format(@post.story)%>
      </div>
      <div class='comment-index'>
        <span class="indispensable">　評価ポイント　</span><br/><br/>
        <%= simple_format(@post.point) %>
      </div>
    </div>

    <div class="comment-new">
      <%= form_with model: @comment, url: post_comments_path, class: 'comment-new-main', local: true do |f| %>
        <div class="field">
          <%= f.text_area :comment, placeholder: "" %>
        </div>
        <div class="btn-contents">
          <%= f.submit "投稿する", data: { turbo_method: :get, turbo_confirm: ( render "shared/error_messages", model: f.object ) } ,class:"post-btn" %>
        </div>
      <% end %>
   </div>
</div>

app/views/comments/show.html.erb
<div class='main-body'>
  <%= render partial: "shared/side_header/post_show", locals: { post: @post }  %>
  
  <div class='menus'>
    <%= render partial: "shared/menus/post_show", locals: { post: @post } %>
  </div>
  
  <div class='main'>
    <%= render partial: "shared/top_header/pt_name", locals: { post: @post } %>

    <div class='post-show'>
      <div class="post-info">
       <%= render partial: "shared/scenario", locals: { post: @post } %>
      </div>
      <div class='comment-index'>
        <div>
          <%= @comment.created_at.strftime('%Y/%m/%d')  %>
          <%= @comment.user.nickname %><br/><br/>
          <%= simple_format(@comment.comment) %>
        </div>

        <div class="comment-edit">
          <% if user_signed_in? %> 
            <% if current_user.id == @comment.user_id %>
               <%= link_to edit_post_comment_path(@post, @comment) do %>
                <%= image_tag("フリーのギアアイコン.png", alt: "シナリオ", class: "header-icon") %> 編集
              <% end %>
              <%= link_to post_comment_path(@post, @comment), data: { turbo_method: :delete, turbo_confirm: "コメントを削除しますか？"} do %>
                <%= image_tag("ごみ箱のフリーアイコン.png", alt: "シナリオ", class: "header-icon") %> 削除
              <% end %>
            <% end %>
          <% end %>
          <%=link_to 'もどる', post_path(@post), class:"back-btn" %>
        </div>
      </div>
    </div>
      <%= render "shared/footer"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fastory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if post.title_id != 2 && post.user != current_user %>
  <% if user_signed_in? && post.liked_by?(current_user)%>
    <%=link_to image_tag("ハートのアイコン素材 1 (青).png", class: "liked-icon"), post_likes_path(post.id), data: { turbo_method: :delete }, class: "post_likes" %>
  <% else %>
    <%=link_to image_tag("ハートのアイコン素材 1 (灰).png", class: "like-icon"), post_likes_path(post.id), data: { turbo_method: :post }, class: "post_likes" %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @post.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @post.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {post: @post}) %>"

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>
<ul class='lists-right'>
  <% if user_signed_in? %>
    <li><%= link_to current_user.nickname, "#", class: "user-nickname" %> </li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "logout"  %></li>
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<div class='main-body'>
  <%= render "shared/side_header/new_or_edit" %>  
  
  <%= form_with model: @post, url: post_path, class: 'post-new-main', id: 'new_post', local: true do |f| %>
    
    <%= render partial: "shared/form", locals: { f: f } %>
    
    <div class='form-end'>
      <div class="btn-contents">
        <%= f.submit "変更する", data: { turbo_method: :get, turbo_confirm: ( render "shared/error_messages", model: f.object ) } %><br/><br/>
        ※画像を編集する際は すべて選びなおしてください<br/>
        　編集しなければ データは失われません

      </div>
    </div>
  <% end %>
  
</div>

app/views/posts/index.html.erb
<div class='main-body'>
  <%= render "shared/side_header/post_index" %>
  
  <div class='menus'>
    <%= render "shared/menus/post_index"%>
  </div>
  
  <div class='main'>
   <%= render "shared/top_header/login" %>

    <div class='post-index'>
      <div class='top-page-image'>
        <%= image_tag("top-image.png", class: "top-image") %>
      </div>
      
      <ul class='post-lists'>
       
        <% @post.each do |post| %>
          <% if post.title_id != 2 %> <%#下書きは表示しないようにする%>
            <li class='post-list'>
              <%= link_to post_path(post) do %>
                <%= post.symptom %>
                <%= Title.find(post.title_id).name %> 
              <% end %>
              <div>
                <%= post.age %>歳 
                <%= Sex.find(post.sex_id).name %>　　　　　
              </div>
              <%= post.user.nickname %>

              <div id="like-btn<%= post.id %>">
                <%= render partial: "likes/like", locals: { post: post } %>
              </div>

            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <%= render "shared/footer"%>
  </div>
</div>

<script src="https://unpkg.com/scrollreveal"></script>
<script>
  ScrollReveal({ 
    reset: false, 
    distance: "10px",
    duration: 3000,
    delay: 200,
    });
  ScrollReveal().reveal('.top-image', { delay: 500, origin: "bottom" });
</script>

app/views/posts/new.html.erb
<div class='main-body'>
  <%= render "shared/side_header/new_or_edit" %>

  <%= form_with model: @post, url: posts_path, class: 'post-new-main', id: 'new_post', local: true do |f| %>
    
    <%= render partial: "shared/form", locals: { f: f } %>

    <div class='form-end'>
      <div class="btn-contents">
        <%= f.submit "投稿する", data: { turbo_method: :get, turbo_confirm: ( render "shared/error_messages", model: f.object ) } %><br/>
        下書き ⇒ カテゴリーを「下書き」 &「★必須」部分を記入<br>
        本書き ⇒ 任意のカテゴリーを選択 &「★必須」「★」部分を記入
      </div>
    </div>
  <% end %>
  
</div>

app/views/posts/search.html.erb
<div class='main-body'>
  <%= render "shared/side_header/post_index" %>
  
  <div class='menus'>
    <%= render "shared/menus/post_index"%>
  </div>
  
  <div class='main'>
   <%= render "shared/top_header/login" %>

    <div class='post-index'>
      <div class='top-page-image'>
        <%= image_tag("top-image.png", class: "top-image") %>
      </div>
      <ul class='post-lists'>

        <% if @posts_by_title.present? %>
          <% @posts_by_title.each do |post| %>
            <li class='post-list'>
              <%= link_to post_path(post) do %>
                <%= post.symptom %>
                <%= Title.find(post.title_id).name %> 
              <% end %>
              <div>
                <%= post.age %>歳 
                <%= Sex.find(post.sex_id).name %>　　　　　
              </div>
              <%= post.user.nickname %>
              <div id="like-btn<%= post.id %>">
                <%= render partial: "likes/like", locals: { post: post } %>
              </div>
            </li>
          <% end %>

        <% else %>
          <% @posts_by_keyword.each do |post| %>
            <li class='post-list'>
              <%= link_to post_path(post) do %>
                <%= post.symptom %>
                <%= Title.find(post.title_id).name %> 
              <% end %>
              <div>
                <%= post.age %>歳 
                <%= Sex.find(post.sex_id).name %>　　　　　
              </div>
              <%= post.user.nickname %>
              <div id="like-btn<%= post.id %>">
                <%= render partial: "likes/like", locals: { post: post } %>
              </div>
            </li>
          <% end %>
        <% end %>

      </ul>
    </div>
    <%= render "shared/footer"%>
  </div>
</div>

<script src="https://unpkg.com/scrollreveal"></script>
<script>
  ScrollReveal({ 
    reset: false, 
    distance: "10px",
    duration: 1000,
    delay: 100,
    });
  ScrollReveal().reveal('.top-image', { delay: 200, origin: "bottom" });
</script>

app/views/posts/show.html.erb
<div class='main-body'>
  <%= render partial: "shared/side_header/post_show", locals: { post: @post } %>
  
  <div class='menus'>
    <%= render partial: "shared/menus/post_show", locals: { post: @post } %>
  </div>
  
  <div class='main'>
    <%= render partial: "shared/top_header/pt_name", locals: { post: @post } %>

    <div class='post-show'>
      <div class='post-info'>
       <%= render partial: 'shared/scenario', locals: { post: @post } %>
      </div>
      <div class='comment-index'>
        <ul class='comment-lists'>
          <% @comment.each do |comment| %>
            <li class='comment-list'>
              <%= link_to post_comment_path(@post, comment) do %>
                実施：<%= comment.created_at.strftime('%Y/%m/%d')  %>
              <% end %>
              <%= comment.user.nickname %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%= render "shared/footer"%>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% else %>
  <%= "確定しますか？" %>
<% end %>

app/views/shared/_error_messages2.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_menus.html.erb
<div class='menus'>
  <div class='menu-top'>
    <div class='logo'>
      <%= link_to image_tag("Fast.png", alt: "Fast", class: "logo-icon"), root_path %>
    </div>
    <div class='user'>
      <% if user_signed_in? %>
        USER：<%= current_user.nickname %>
      <% end %>
    </div>
    </div>
  
  <div class='menu'>
    <%= link_to new_post_path, class: "new-post" do %>
      <%= image_tag("メモ帳、書類のアイコン素材 その3.png", alt: "メモ帳のフリーアイコン素材", class: "image-icon") %>
      NEWシナリオを作成する
    <% end %>  
  </div>
</div>

app/views/shared/_scenario.html.erb
<div>
  <% if post.title_id != 2 %> <%#下書きは表示しないようにする%>
    主訴：<%= post.symptom%><br/>
    <%= simple_format(post.event) %><br/><br/>

    気道：<%= post.airway %><br/>
    呼吸：<%= post.breathing %><br/>
    循環：<%= post.circulation %><br/>
    意識：<%= post.dysfunction_cns %><br/>
    <%= post.exposure %><br/><br/>

    アレルギー：<%= post.allergy %><br/>
    服薬歴：<%= post.medicine %><br/>
    既往歴：<%= post.past_history %><br/>
    最終飲食：<%= post.last_meal %><br/>
    危険因子：<%= post.risk_factor %><br/>
    同乗者：<%= post.family %><br/>
    <%= post.others %><br/>
  <% else %>
   下書きは閲覧できません
  <% end %>
</div>

app/views/shared/menus/_post_index.html.erb
  <div class='menu-top'>
    <%= link_to image_tag("Fast.png", alt: "Fast", class: "logo-icon"), root_path %>
  </div>
  
  <div class='menu'>
    <%= link_to new_post_path, class: "new-post" do %>
      <%= image_tag("メモ帳、書類のアイコン素材 その3 (1).png", alt: "メモ帳のフリーアイコン素材", class: "image-icon") %>
      NEW
    <% end %>  
    <%= link_to search_posts_path, class: "new-post" do %>
      <%= image_tag("検索用の虫眼鏡アイコン素材.png", alt: "検索用の虫眼鏡アイコン", class: "image-icon") %>
      SEARCH
    <% end %> 
    <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %>
      <div class="form-group">
        <%= text_field_tag 'keyword', params[:keyword], placeholder: '主訴を検索する', class: 'search-input' %>
      </div>

      <div class="form-group">
        <%= select_tag 'title_id', options_from_collection_for_select(Title.all, 'id', 'name', params[:title_id]), class: 'search-input' %>
      </div>
      <div class="btn-contents">
        <%= submit_tag '検索' %>
      </div>
    <% end %>
  </div>

app/views/shared/menus/_post_show.html.erb
  <div class='menu-top'>
    <%= link_to image_tag("Fast.png", alt: "Fast", class: "logo-icon"), root_path %>
  </div>
  
  <div class='menu'>
    <div class='post-images'>
      <% if post.title_id != 2 %> <%#下書きは表示しないようにする%>

        <% if post.images.attached? %>
          <%= link_to post.images[0] do %>
            <%= image_tag "肺のアイコン素材 4 (1).png", class: "image-icon" %>
            <%= post.images[0].filename if post.images[0] %>
          <% end %>
          <%= link_to post.images[1] do %>
            <%= image_tag "ハートの心電図のアイコン素材 2.png", class: "image-icon" %>
            <%= post.images[1].filename if post.images[1] %>
          <% end %>
          <%= link_to post.images[2] do %>
            <%= image_tag "水滴アイコン4.png", class: "image-icon" %>
            <%= post.images[2].filename if post.images[2] %>
          <% end %>
          <%= link_to post.images[3] do %>
            <%= image_tag "献血アイコン1 (1).png", class: "image-icon" %>
            <%= post.images[3].filename if post.images[3] %>
          <% end %>
          <%= link_to post.images[4] do %>
            <%= image_tag "電波、ビーコンのアイコン.png", class: "image-icon" %>
            <%= post.images[4].filename if post.images[4] %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class='menu-editor'>
      <% if user_signed_in? %> 
        <% if post.title_id != 2 %> <%#下書きは表示しないようにする%>
          <%= link_to "シナリオを実施する", post_comments_path(@post), data: { turbo_method: :get, turbo_confirm: "シナリオを開始しますか？"} %><br/>
        <% end %>
        <% if current_user.id == @post.user_id %>
          <%= link_to edit_post_path(@post) do %>
            <%= image_tag("フリーのギアアイコン.png", alt: "シナリオ", class: "header-icon") %>シナリオ 編集
          <% end %>
          <%= link_to post_path(@post), data: { turbo_method: :delete, turbo_confirm: "シナリオを削除しますか？ 一度消すと元に戻せません！"} do %>
            <%= image_tag("ごみ箱のフリーアイコン.png", alt: "シナリオ", class: "header-icon") %>シナリオ 削除
          <% end %>
        <% end %>
      <% end %>
      <%=link_to 'トップへもどる', root_path, class:"back-btn" %>
    </div>
  </div>

app/views/shared/menus/_user_show.html.erb
  <div class='menu-top'>
    <%= link_to image_tag("Fast.png", alt: "Fast", class: "logo-icon"), root_path %>
  </div>
  
  <div class='menu'>
    <%= link_to new_post_path, class: "new-post" do %>
      <%= image_tag("メモ帳、書類のアイコン素材 その3 (1).png", alt: "メモ帳のフリーアイコン素材", class: "image-icon") %>
      NEW
    <% end %>
    
    <%= link_to edit_user_registration_path, class: "new-post" do %>
      <%= image_tag("人物のアイコン素材 その3.png", alt: "人物のアイコン", class: "image-icon") %>
      EDIT
    <% end %>

    <div class="total-like", style="display: flex; align-items: center;">
      <%= image_tag "ハートのアイコン素材 1 (灰).png", class: "image-icon" %>
      <span style="margin: 0 0 20px 5px;"><%= "×#{@user.posts.joins(:likes).count}" %></span>
    </div>
    
  </div>